name: CI

on:
  push:
    branches: [ mob, ci ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: Do All Tests
    runs-on: ubuntu-latest
    steps:

    - name: Make Directories
      run: |
        mkdir tinycc-stage1/
        mkdir tinycc-stage2/
        mkdir tinycc-stage3/
    - name: Checkout Clean
      uses: actions/checkout@v4
      with:
        path: tinycc-clean-src/
        repository: TinyCC/tinycc
        ref: 6120656cbf6d772fd30a18d5ba950d39c99ba226
    - name: Checkout RoTT
      uses: actions/checkout@v4
      with:
        path: tinycc-rott-src/

    - name: Build and Test Stage 1
      working-directory: tinycc-rott-src/
      run: |
        ./configure --prefix=${GITHUB_WORKSPACE}/tinycc-stage1/
        make
        make test -k
        make install
        make distclean
    - name: Build and Test Stage 2
      working-directory: tinycc-clean-src/
      run: |
        ./configure --prefix=${GITHUB_WORKSPACE}/tinycc-stage2/ --cc=${GITHUB_WORKSPACE}/tinycc-stage1/bin/tcc
        make
        make test -k
        make install
        make distclean
    - name: Build Stage 3
      working-directory: tinycc-clean-src/
      run: |
        ./configure --prefix=${GITHUB_WORKSPACE}/tinycc-stage3/ --cc=${GITHUB_WORKSPACE}/tinycc-stage2/bin/tcc
        make
        make install
        make distclean

    - name: Check Stage 3 Equals Stage 2
      run: diff tinycc-stage2/bin/tcc tinycc-stage3/bin/tcc
