name: CI

on:
  push:
    branches: [ mob, ci ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: Run Conventional Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: ./configure
    - name: Build
      run: make
    - name: Test
      run: make test -k
