name: CI

on:
  push:
    branches: [ mob, ci ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-1:
    name: Run Conventional Tests On Stage 1
    runs-on: ubuntu-22.04
    steps:
    - name: Make Directories
      run: mkdir tinycc-bin/
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: tinycc-rott/
    - name: Change Directory
      run: cd tinycc-rott/
    - name: Build and Install
      run: |
        ./configure --prefix=${GITHUB_WORKSPACE}/tinycc-bin/
        make
        make install
    - name: Test
      run: make test -k
