name: build and run tests

on:
  push:
    branches: [ mob ]

jobs:
  test-x86_64-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: make & test tcc
      run: ./configure && make && make test -k
